2025-03-28 15:59:25,472 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-03-28 16:07:02,073 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-03-28 16:07:08,708 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    self._apply_styling()
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    if not self.table or not self.current_data:
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:17:19,426 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:19:28,493 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:21:00,224 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:23:36,760 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:24:31,211 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:25:07,414 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 16:34:21,531 - hades - ERROR - Erro ao carregar dados combinados: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 440, in refresh_data
    self.inventory_view.display_data(df)
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 62, in display_data
    )
  File "C:\Users\miqueias.silva\Documents\HADES\ui\inventory_view.py", line 69, in _apply_styling
    self.status_var.set(f"Exibindo {len(data)} registros | {len(data.columns)} colunas")
                             ^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-28 17:17:06,440 - hades - ERROR - Erro ao carregar imagem inicial: [Errno 2] No such file or directory: 'hades.jpg'
2025-03-28 17:31:32,050 - hades - ERROR - Erro ao carregar splash: [Errno 2] No such file or directory: 'C:\\Users\\miqueias.silva\\Documents\\HADES\\ui\\assets\\hades.jpeg'
2025-03-28 17:33:20,180 - hades - ERROR - Erro ao carregar splash: module 'PIL.Image' has no attribute 'ANTIALIAS'
2025-03-28 17:38:32,959 - hades - WARNING - Imagem splash não encontrada nos locais:
2025-03-28 17:38:32,959 - hades - WARNING - - C:\Users\miqueias.silva\Documents\HADES\ui\assets\hades.jpeg
2025-03-28 17:38:32,959 - hades - WARNING - - C:\Users\miqueias.silva\Documents\HADES\ui\hades.jpeg
2025-03-28 17:38:32,959 - hades - WARNING - - C:\Users\miqueias.silva\Documents\HADES\ui\ui\assets\hades.jpeg
2025-04-01 15:19:35,615 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-04-01 15:19:38,304 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:19:57,896 - hades - ERROR - Erro ao carregar dados combinados: Invalid column metadata (corrupt file?)
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 513, in refresh_data
    df = pd.read_parquet(combined_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parquet.py", line 274, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarrow\parquet\core.py", line 1843, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\miqueias.silva\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarrow\parquet\core.py", line 1485, in read
    table = self._dataset.to_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\\_dataset.pyx", line 574, in pyarrow._dataset.Dataset.to_table
  File "pyarrow\\_dataset.pyx", line 3865, in pyarrow._dataset.Scanner.to_table
  File "pyarrow\\error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
OSError: Invalid column metadata (corrupt file?)
2025-04-01 15:25:16,580 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:25:20,220 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:25:20,460 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:25:20,643 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:25:43,590 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:25:55,163 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-01 15:27:37,432 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 11:15:36,449 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 11:27:27,509 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-04-03 11:48:35,003 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-04-03 12:00:31,259 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-04-03 12:08:42,039 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-04-03 13:55:17,768 - hades - INFO - Nenhum arquivo de dados combinados encontrado
2025-04-03 14:49:06,104 - hades - ERROR - Erro ao criar inventÃ¡rio: 'ConfigManager' object is not callable
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 280, in _handle_create_inventory
    with self._operation_in_progress():
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 480, in __enter__
    self.window.set_cursor("watch")
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 512, in set_cursor
    self.config(cursor=cursor_type)
TypeError: 'ConfigManager' object is not callable
2025-04-03 14:53:09,486 - hades - ERROR - Erro ao criar inventÃ¡rio: 'ConfigManager' object is not callable
Traceback (most recent call last):
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 280, in _handle_create_inventory
    with self._operation_in_progress():
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 480, in __enter__
    self.window.set_cursor("watch")
  File "C:\Users\miqueias.silva\Documents\HADES\ui\main_window.py", line 512, in set_cursor
    self.config(cursor=cursor_type)
TypeError: 'ConfigManager' object is not callable
2025-04-03 14:55:16,119 - hades - INFO - Processando...
2025-04-03 14:55:17,052 - hades - INFO - Processando...
2025-04-03 14:55:17,073 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 14:55:17,084 - hades - INFO - Pronto
2025-04-03 14:55:18,902 - hades - INFO - Pronto
2025-04-03 14:55:35,305 - hades - INFO - Processando...
2025-04-03 14:55:35,347 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 14:55:35,349 - hades - INFO - Pronto
2025-04-03 14:55:40,801 - hades - INFO - Processando...
2025-04-03 15:14:31,266 - hades - INFO - Processando...
2025-04-03 15:15:54,470 - hades - INFO - Processando...
2025-04-03 15:24:46,194 - hades - INFO - Processando...
2025-04-03 15:24:46,344 - hades - INFO - Processando...
2025-04-03 15:24:46,379 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 15:24:46,379 - hades - INFO - Pronto
2025-04-03 15:24:47,655 - hades - INFO - Pronto
2025-04-03 15:25:07,722 - hades - INFO - Processando...
2025-04-03 15:25:07,764 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 15:25:07,765 - hades - INFO - Pronto
2025-04-03 15:25:13,530 - hades - INFO - Processando...
2025-04-03 15:28:17,068 - hades - INFO - Pronto
2025-04-03 15:40:48,050 - hades - INFO - Processando...
2025-04-03 15:40:49,063 - hades - INFO - Processando...
2025-04-03 15:40:49,129 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 15:40:49,129 - hades - INFO - Pronto
2025-04-03 15:40:50,189 - hades - INFO - Pronto
2025-04-03 15:41:02,581 - hades - INFO - Processando...
2025-04-03 15:41:02,612 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 0
2025-04-03 15:41:02,632 - hades - INFO - Pronto
2025-04-03 15:41:12,455 - hades - INFO - Processando...
2025-04-03 15:41:14,590 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 1106652
2025-04-03 15:41:14,590 - hades - INFO - Pronto
2025-04-03 15:42:12,767 - hades - INFO - Processando...
2025-04-03 15:42:17,900 - hades - INFO - Dados carregados | Itens com excesso: 0 | Itens faltando: 0 | Total: 1106652
2025-04-03 15:42:17,941 - hades - INFO - Pronto
2025-04-03 15:42:22,341 - hades - INFO - Processando...
2025-04-03 15:42:24,579 - hades - INFO - Dados carregados | Itens com excesso: 1307 | Itens faltando: 0 | Total: 1106652
2025-04-03 15:42:24,579 - hades - INFO - Pronto
2025-04-03 15:49:46,257 - hades - INFO - Processando...
2025-04-03 15:49:51,515 - hades - INFO - Dados carregados | Itens com excesso: 1307 | Itens faltando: 0 | Total: 1106652
2025-04-03 15:49:51,516 - hades - INFO - Pronto
